FROM ruby:3.4.3

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    default-mysql-client \
    default-libmysqlclient-dev \
    nodejs \
    npm \
    git \
    curl

# Install Yarn
RUN npm install -g yarn

# Set working directory
WORKDIR /app

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application code
COPY . .

# Expose port
EXPOSE 3000

# Start server
CMD ["rails", "server", "-b", "0.0.0.0"]

